#!/bin/sh

# Les dependences - webtorrent, dmenu, libxml

mkdir -p $HOME/.cache/notflix-fr

# Marre des changements de domaine... je le recup ici
updatedomain="torrent9.nl"

menu="dmenu -i -l 25"
baseurl="https://www.$updatedomain"
cachedir="$HOME/.cache/notflix-fr"
useragent="Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/81.0"

if [ -z $1 ]; then
  query=$(dmenu -p "Recherche 📽: " <&-)
else
  query=$1
fi

query="$(echo $query | sed 's/ /+/g')"
curl -A $useragent -s $baseurl/recherche/$query > $cachedir/tmp.html

# je recup que la table des torrents
xmllint --html --xpath '//tr' $cachedir/tmp.html > $cachedir/tmplinks.html 2>/dev/null

# Les titres
grep -o '<a href="/torrent/.*</a>' $cachedir/tmplinks.html |
  sed 's/<[^>]*>//g' > $cachedir/titles.bw

result_count=$(wc -l $cachedir/titles.bw | awk '{print $1}')
if [ "$result_count" -lt 1 ]; then
  notify-send "😔 Pas de torrents disponibles correspondant à votre recherche." -i "NONE"
  exit 0
fi

# Seeders / Leechers
grep -o '<td .* alt="seeders"/>.*</td>\|<td .* alt="leechers"/>.*</td>' $cachedir/tmplinks.html |
  sed 's/<[^>]*>//g' | sed 'N;s/\n/ /' > $cachedir/seedleech.bw

# La taille du fichier
grep -o '<td width="11%" align="left">.*</td>' $cachedir/tmplinks.html |
  sed 's/<span class="seeds">.*<\/span>//g' |
  sed -e 's/<[^>]*>//g' > $cachedir/size.bw

# Les liens
grep -E '/torrent/' $cachedir/tmplinks.html > $cachedir/links.html
xmllint --html --xpath '//a/@href' $cachedir/links.html > $cachedir/linkshref.bw 2>/dev/null
sed 's/ href=//g' $cachedir/linkshref.bw | sed 's/"//g' > $cachedir/links.bw

# Nettoyage de certaines informations à afficher
sed 's/\./ /g; s/\-/ /g' $cachedir/titles.bw |
  sed 's/[^A-Za-z0-9 ]//g' | tr -s " " > $cachedir/tmp && mv $cachedir/tmp $cachedir/titles.bw

awk '{print NR " - ["$0"]"}' $cachedir/size.bw > $cachedir/tmp && mv $cachedir/tmp $cachedir/size.bw
awk '{print "[S:"$1 ", L:"$2"]" }' $cachedir/seedleech.bw > $cachedir/tmp && mv $cachedir/tmp $cachedir/seedleech.bw

# Getting the line number
LINE=$(paste -d\   $cachedir/size.bw $cachedir/seedleech.bw $cachedir/titles.bw |
  $menu |
  cut -d\- -f1 |
  awk '{$1=$1; print}')

if [ -z "$LINE" ]; then
  notify-send "A la prochaine..." -i "NONE"
  exit 0
fi
notify-send "🔍 Recherche du lien Magnet et lancement." -i "NONE"
url=$(head -n $LINE $cachedir/links.bw | tail -n +$LINE)
fullURL="${baseurl}${url}"

# Recherche du lien magnet
echo $fullURL
curl -A "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/81.0" -s $fullURL > $cachedir/tmpmagnet.html
magnet=$(grep -Po "magnet:\?xt=urn:btih:[0-9a-fA-F]{40,}.*(?=';)" $cachedir/tmpmagnet.html | head -n 1) 

# C'est parti mon kiki
webtorrent "$magnet" --vlc
